version: 1.4.9.8a{build}
max_jobs: 15
image: Visual Studio 2017
configuration: Release
platform: x86
test: off

before_build:
- cmd: call ci_build.bat

cache:
  - .\externals\cpython
  - .\externals\aes
  - .\obj
  - .\bin

build:
  project: Els_kom_Solution.sln
  parallel: true
  verbosity: minimal
