version: 1.4.9.8a{build}
skip_branch_with_pr: true
max_jobs: 15
image: Visual Studio 2017
configuration: Release
platform: x86
build:
  project: PCbuild\pcbuild.sln
  parallel: true
  verbosity: minimal
test: off
artifacts:
- path: bin/$(platform)/$(configuration)/*.zip
  name: myartifact
before_deploy:
- ps: IF ($env:APPVEYOR_REPO_TAG -eq "true") {$env:APPVEYOR_REPO_TAG_NAME = $env:version}
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  auth_token:
    secure: oHqKZpK6huL4v9LT6ifeFb/MA3vI1NRlN66jP+qbI7DiGhV0ZF3L7xmTeJR+OEFG
  repository: Elskom/Els_kom_builds
  artifact: myartifact
  force_update: true
  on:
    platform: x86
#   branch: master
#   appveyor_repo_tag: true
