version: 1.4.9.8a{build}
max_jobs: 15
image: Visual Studio 2017
configuration: Release
platform: x86
before_build:
- cmd: call get_externals.bat && call externals\cpython\PCBuild\build.bat
build:
  project: Els_kom_Solution.sln
  parallel: true
  verbosity: minimal