version: 1.4.9.8a{build}
# skip_branch_with_pr: true
max_jobs: 15
image:
- Visual Studio 2017
- Visual Studio 2017 Preview
configuration: Release
platform: x86
before_build:
- cmd: >-
    cd externals

    git clone https://github.com/Elskom/newsmake.git

    cd newsmake/build

    cmake ..

    msbuild newsmake.sln /p:Configuration=Release /p:Platform="Win32" /nologo /verbosity:m /m

    cd ../../

    git clone https://github.com/Elskom/ZLIB.NET.git --branch patches

    cd ../Misc/NEWS

    "../../externals/newsmake/build/Release/newsmake"

    cd ../..
build:
  project: PCbuild\pcbuild.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    cd bin/x86/Release/

    IF EXIST "Els_kom_new.zip" (

    del "Els_kom_new.zip"

    )

    IF EXIST "Symbols.zip" (

    del "Symbols.zip"
    )

    "Els_kom" -p Els_kom_new.zip

    "Els_kom" -d Symbols.zip

    cd ../../..
test: off
artifacts:
- path: bin/$(platform)/$(configuration)/*.zip
  name: myartifact
before_deploy:
- ps: IF ($env:APPVEYOR_REPO_TAG -eq "false") {$env:APPVEYOR_REPO_TAG_NAME = "v" + $env:APPVEYOR_BUILD_VERSION}
deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: '$(APPVEYOR_REPO_COMMIT_MESSAGE) - $(APPVEYOR_REPO_BRANCH)'
  auth_token:
    secure: oHqKZpK6huL4v9LT6ifeFb/MA3vI1NRlN66jP+qbI7DiGhV0ZF3L7xmTeJR+OEFG
  repository: Elskom/Els_kom_builds
  artifact: myartifact
  force_update: true
  on:
    platform: x86
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: '$(APPVEYOR_REPO_COMMIT_MESSAGE) - $(APPVEYOR_REPO_BRANCH)'
  auth_token:
    secure: oHqKZpK6huL4v9LT6ifeFb/MA3vI1NRlN66jP+qbI7DiGhV0ZF3L7xmTeJR+OEFG
  repository: Elskom/Els_kom_builds
  artifact: myartifact
  prerelease: true
  force_update: true
  on:
    platform: x86
    APPVEYOR_REPO_TAG: false
